version: '2'
services:
  db:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'bikerails'
      POSTGRES_PASSWORD: '26111979'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass 26111979
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/bikerails'
    env_file:
      - '.env'
  web:
    build: .
    command:  foreman start -f Procfile.hot
    volumes:
      - .:/bikerails
    ports:
      - "3000:3000"
      - "3500:3500"
    depends_on:
      - db
      - redis
volumes:
  redis:
  postgres: