version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command:  foreman start -f Procfile.hot
    volumes:
      - .:/bikerails
    ports:
      - "3000:3000"
      - "3500:3500"
    depends_on:
      - db
